name: Windows 10 - HopToDesk

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 9999
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/6mxum60ljukokzn4flb8n/Down.bat?rlkey=jjflao3yvizf2a2ye0q5mln9d&dl=1" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Log In To HopToDesk
        run: cmd /c show.bat

      - name: Time Counter
        run: python time.py
